index.html
package-lock.json
package.json
public/marker.svg
src/components/button.tsx
src/components/kakao-map.tsx
src/index.css
src/pages/home.tsx
src/styled.d.ts
src/styles/shared/theme.ts
tsconfig.json

[[ Feature ] 카카오 지도 api 연동 및 마커 생성 + 사용자 장소 입력](https://github.com/IT-Cotato/9th-Midpoint-FE/issues/1)
- [x ] 새로운 기능 추가
카카오 지도 api 연동 및 마커 생성 + 사용자 장소 입력
1. '중간 지점 찾기' 버튼은 form제출로 처리하며, 이때 해당 form에 문제가 없을 시에는
'중간 지점 찾기' api요청을 하고 정상적으로 처리된 경우, 응답받은 값을 navigate의 state에 저장하여
'중간 지점 찾기'를 보여주는 페이지로 이동 시킨다
2. 친구들의 목록의 수 만큼 입력란(이름, 운송수단, 위치) 을 보여주도록 한다.
3.  버튼 클릭시 '이름 , 운송수단, 위치' 를 입력할 수 있는 입력란을 추가한다.
- 버튼 클릭시 친구 목록에 아래와 같은 형식의 친구 목록의 placeholder를 추가한다.
- {username: '이름', transport: '지하철' address: '도로명 주소' }
4. 각각의 사용자는 '이름, 운송수단, 위치' 정보를 입력해야 하며, 해당 칸이 비어 있는 경우에는 '중간지점찾기' 버튼 클릭시 에러메세지를 반환한다
1. 지도위에 마커로 보여주는 과정은 사용자가 위치를 검색하고 해당 위치를 클릭한 직후,
해당 좌표값을 통해 카카오 지도위에 마커를 표시해주는 함수로 처리하도록 한다
1-1. 이때 사용자가 주소입력 완료 후 다시 주소를 찾아 주소를 바꾸게 되는경우
바뀐 주소에 해당 하는 위치가 지도에 반영되도록 한다.
1-2. 여러명이 주소를 입력하는 경우, 다른 사람이 주소를 …

✨ feat: 카카오 지도 api 연동 및 마커 생성 + 사용자 장소 입력

---

src/components/kakao-map.tsx

fix: 빌드 파일 오류 해결

---

package-lock.json
package.json
src/apis/enter-location.ts
src/apis/index.ts
src/components/button.tsx
src/components/login.tsx
src/pages/enter-location.tsx
src/pages/home.tsx
src/pages/loading.tsx
src/pages/location-alone.tsx
src/pages/location-each.tsx
src/pages/not-found.tsx
src/routes/router.tsx
src/stores/login-state.ts

[issue #8 ](https://github.com/IT-Cotato/9th-Midpoint-FE/issues/7)
어떤 변경 사항이 있나요?
+ 개개인이 따로 장소를 입력하게 되는 경우에 대한 페이지 구성
+ 개개인 장소 입력 페이지 api 연동 코드 작성

✨ feat: 개개인 장소 입력 화면 구현 및 api 연동 코드 작성

---

src/pages/location-each.tsx

[issue7](https://github.com/IT-Cotato/9th-Midpoint-FE/issues/7)
어떤 변경 사항이 있나요?
- [] 파일 혹은 폴더 삭제
+ 개개인이 장소를 입력하는 페이지 구현
+ 개개인 장소 입력 페이지에 대한 api 연동 코드 작성

✨ feat: 개개인 장소 입력 화면 구현 및 api 연동 코드 작성 

---

src/apis/login.ts
src/components/login.tsx
src/pages/location-each.tsx

[Issue #14 ](https://github.com/IT-Cotato/9th-Midpoint-FE/issues/14)
어떤 변경 사항이 있나요?
개개인 장소 입력과정에서, 로그인이 되어 있지 않을 경우, 로그인 화면이 보이도록 구현하였습니다.
또한 로그인 성공시, 장소입력을 받을 수 있도록 구현하였습니다

✨ feat: 로그인 컴포넌트 구현

---

src/apis/enter-location.ts
src/apis/login.ts
src/apis/midpoint-results.ts
src/components/MidpointResult.tsx
src/components/PlaceModal.tsx
src/components/ProtectedRoute.tsx
src/components/location-each-form.tsx
src/components/login.tsx
src/constants/index.ts
src/pages/location-alone.tsx

fix: api연동 변경사항 반영 #26

---

src/components/MidpointResult.tsx
src/pages/location-alone.tsx

fix: api연동 수정 #26

---

src/components/time/calendar.tsx
src/components/time/vote-calendar.tsx
src/pages/time.tsx

fix: type err

---

src/apis/index.ts
src/routes/router.tsx

fix: api 응답코드 수정

---

src/apis/enter-location.ts
src/pages/Location/location-alone.tsx
src/pages/Location/location-each.tsx
src/pages/MidpointResult/MidpointAloneResult.tsx
src/pages/MidpointResult/MidpointEachResult.tsx
src/pages/Recommend/RecommendAlone.tsx
src/pages/Recommend/RecommendEach.tsx

fix: axiosInstance반영

---

src/pages/Recommend/RecommendAlone.tsx
src/pages/Recommend/RecommendEach.tsx

fix: 페이지네이션 오류 수정

---

src/apis/index.ts

fix: refresh 수정

---

src/pages/PlaceVote/Result/PlaceResultAlone.tsx
src/pages/PlaceVote/Result/PlaceResultEach.tsx

feat: 장소투표 구현

---

src/apis/timeVoteRoom.ts
src/components/Navbar/Navbar.tsx
src/constants/index.ts
src/pages/Location/location-alone.tsx
src/pages/Location/location-each.tsx
src/pages/Login/login.tsx
src/pages/TimeVote/Create/TimeCreateAlone.tsx
src/pages/TimeVote/Create/TimeCreateEach.tsx
src/pages/TimeVote/Result/TimeResultAlone.tsx
src/pages/TimeVote/Result/TimeResultEach.tsx
src/pages/TimeVote/Vote/TimeVoteAlone.tsx
src/pages/TimeVote/Vote/TimeVoteEach.tsx
src/routes/router.tsx

feat: 시간투표기능

---

src/components/Modal/PlaceModal.tsx

feat: placemodal 수정

---

src/components/Modal/PlaceModal.tsx

fix: api 수정

---

src/components/Modal/PlaceModal.tsx

fix: caching문제 해결

---

src/apis/index.ts
src/components/common/shared/BannerMessage.tsx
src/pages/Home/home.tsx
src/pages/Login/login.tsx

feat: 배너메세지 경로별 수정

---

src/components/Modal/PlaceModal.tsx
src/components/common/shared/BannerMessage.tsx

style: banner 디자인 수정

---

src/components/common/shared/BannerMessage.tsx

style: "banner 디자인 수정"

---

src/components/time/calendar.tsx
src/components/time/vote-calendar.tsx
src/components/time/vote-date-picker.tsx
src/components/time/vote-date.tsx
src/pages/Time/time.tsx
src/pages/TimeResult/time-result.tsx
src/pages/TimeVote/time-vote.tsx

[ Fix ] 시간투표 로직

---

src/components/Modal/PlaceModal.tsx
src/components/common/Button/button.tsx
src/components/time/calendar.tsx
src/components/time/vote-date-picker.tsx
src/pages/Location/location-alone.tsx
src/pages/Location/location-each.tsx
src/pages/MidpointResult/MidpointEachResult.tsx
src/pages/PlaceVote/Result/PlaceResultAlone.tsx
src/pages/PlaceVote/Result/PlaceResultEach.tsx
src/pages/TimeResult/time-result.tsx
src/pages/TimeVote/time-vote.tsx

[ Fix ] style

---

src/components/Navbar/Navbar.tsx
src/components/time/calendar.tsx
src/components/time/vote-date.tsx
src/pages/Home/home.tsx
src/pages/Location/location-alone.tsx
src/pages/Location/location-each.tsx
src/pages/Login/login.tsx
src/pages/PlaceVote/Create/CreateAlone.tsx
src/pages/PlaceVote/Create/CreateEach.tsx
src/pages/PlaceVote/Result/PlaceResultAlone.tsx
src/pages/PlaceVote/Result/PlaceResultEach.tsx
src/pages/PlaceVote/Vote/VoteAlone.tsx
src/pages/PlaceVote/Vote/VoteEach.tsx
src/pages/TimeResult/time-result.tsx
src/pages/TimeVote/time-vote.tsx

style: css 최종 수정

---

src/components/Modal/PlaceModal.tsx

fix: api route경로

---

src/components/Modal/PlaceModal.tsx

fix: api route 수정
